# site settings
title: Ruiyang's Page
subtitle: 
email: dry950526@gmail.com
job: Microservices and Backend Developer at A+ LMS, Aalto University.
study: Master student in Cloud Computing and Services, double degree(Aalto University + TU Delft)
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dingruiyang.pw/
author: Ruiyang Ding 丁瑞洋
street_address:
city: Espoo
state: 
zip_code: 
country: Finland
phone:


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/JohnDing1995/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown


sass:
  style: compressed
